//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOkulEntities : DbContext
    {
        public DbOkulEntities()
            : base("name=DbOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_BRANSLAR> TBL_BRANSLAR { get; set; }
        public virtual DbSet<TBL_ilceler> TBL_ilceler { get; set; }
        public virtual DbSet<TBL_iller> TBL_iller { get; set; }
        public virtual DbSet<TBL_OGRENCILER> TBL_OGRENCILER { get; set; }
        public virtual DbSet<TBL_OGRETMENLER> TBL_OGRETMENLER { get; set; }
        public virtual DbSet<TBL_VELILER> TBL_VELILER { get; set; }
    }
}
